services:
  auto:
    image: hivecv/avatar-generator:main
    build:
      context: .
      dockerfile: webui.dockerfile
    ports:
      - "7860:7860"
      - "8000:8000"
    volumes:
      - ./data:/data
    environment:
      POSTHOG_KEY: ${POSTHOG_KEY}
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
