services:
  auto:
    ports:
      - "7860:7860"
      - "8000:8000"
    volumes:
      - ./data:/data
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    build:
      context: .
      dockerfile: webui.dockerfile
